#!/usr/bin/expect

set timeout 60
set wallet_name $env(wallet_name)
set netuid "64"
set hotkey $env(hotkey)
set password $env(password)

spawn btcli stake remove --wallet-name $wallet_name --netuid $netuid --hotkey-ss58-address $hotkey

expect {
    "Unstake all*" {
        send "y\r"
    }
}

expect {
    "Would you like to continue?" {
        send "y\r"
    }
}

expect "Enter your password:"
send "$password\r"

exit 0